### ISSUE TITLE
Send/Request Hush

### ISSUE THREAD

**Issue by UrgeyBergy** [DenioD/SilentDragonLite-1#72] opened 2020-05-29 17:19 UTC
This was discussed in Discord but not seeing an issue yet, so putting it out here.
Would be nice to have a payment portal on HushChat
Right click a contact displays a drop down of options
One being "Send or Request Hush"
From this option, a popup appears
User types in desired amount of Hush
Radio buttons for "Send" or "Request"
Submit button

**Comment by leto** [comment] 2020-06-12 19:57
@UrgeyBergy considering this a dupe of https://github.com/MyHush/SilentDragonLite/issues/153

if you right click on a contact, we have some placeholders

**Closed as completed by leto** 2020-06-12 19:57 UTC
Labels: v1
